subject = "General questions"

questions_and_answers = {
    "A dog sweats by panting its tongue.": False,
    "A monkey was the first non-human to go into space.": False,
    "A potato was the first vegetable to be planted on the space shuttle.": True,
    "Aladdin's character was based on Brad Pitt.": False,
    "Alaska has the most active volcanoes of any state in the United States.": True,
    "All the kings in a standard deck of cards have a mustache.": False,
    "An ant can lift 1,000 times its body weight.": False,
    "An astronaut has played golf on the moon.": True,
    "An octopus has seven hearts.": False,
    "Bats are blind.": False,
    "Beauty and the Beast was Disney's first Broadway musical.": True,
    "Brazil is the only nation to have played in every World Cup finals tournament.": True,
    "Caesar Salad originates from Italy.": False,
    "Cheesecake comes from Italy.": False,
    "China has the longest coastline in the world.": False,
    "Dr. Pepper is the oldest soft drink in America.": True,
    "Dumbo is the shortest Disney film.": True,
    "Ears of corn have an even number of rows.": True,
    "Every country in the world has a rectangular flag.": False,
    "Every golf ball has the same number of dimples.": False,
    "Football players started wearing helmets in 1943.": True,
    "Fortune cookies were invented in China.": False,
    "French fries originated from France.": False,
    "Galapagos tortoises sleep up to 16 hours a day.": True,
    "Greenland is the largest island in the world.": True,
    "Hawaiian pizza comes from Canada.": True,
    "Henry VIII had eight wives.": False,
    "Herbivores are animal eaters.": False,
    "Human skin regenerates every week.": False,
    "Humans lose an average of 75 strands of hair a month.": False,
    "Humans lose more than 80% of heat from their feet.": False,
    "Infants have more bones than adults.": True,
    "It takes a sloth two weeks to digest a meal.": True,
    "It took eight months from start to finish to produce the 1959 Disney film, Sleeping Beauty.": False,
    "John Glenn became the oldest astronaut when he traveled to space at the age of 53.": False,
    "Marvel published its first comic in October 1939.": True,
    "Mcdonald's has the most restaurants by location in the United States.": False,
    "Memorial Day has a special set of instructions regarding raising and lowering the U.S. flag.": True,
    "Minnie Mouse's full name is Wilhelmina Mouse.": False,
    "Most of the human brain is made of muscle.": False,
    "Mount Everest is the tallest mountain in the world.": True,
    "New York City is composed of between 36 and 42 islands.": True,
    "Only two men signed the Declaration of Independence on July 4, 1776.": True,
    "People who have chiclephobia are afraid of cats.": False,
    "Pepperoni is the most popular pizza topping in the US.": True,
    "Pepsi was the first soft drink to be enjoyed in outer space.": False,
    "Pigs roll in the mud because they don't like being clean.": False,
    "Pineapples grow on trees.": False,
    "Pinocchio was the first animated, full-color Walt Disney feature film.": False,
    "Pizza was the first food consumed in space.": False,
    "Polo takes up the largest amount of space in terms of land area.": True,
    "President George Washington brought macaroni and cheese to the USA.": False,
    "Prince Eric and Ariel from The Little Mermaid have a daughter named Princess Song.": False,
    "Punxsutawney Phil is just a nickname for the famous groundhog.": True,
    "Santa Claus has his own postal code.": True,
    "Sea otters have a favorite rock they use to break open food.": True,
    "Sharks are mammals.": False,
    "Soccer (football) is estimated to have more than 2 billion fans around the world.": False,
    "South Africa has one capital.": False,
    "Taste buds can only be found on the tongue.": False,
    "The Aristocats was the first film to be made after Walt Disney's death.": True,
    "The Atlantic Ocean is the biggest ocean on Earth.": False,
    "The average human sneeze can be clocked at 100 miles an hour.": True,
    "The blue whale is the biggest animal to have ever lived.": True,
    "The Chinese New Year is celebrated on the same day every year.": False,
    "The Chunnel between England and France is 31.5 miles long.": True,
    "The first St. Patrick's Day parade in the United States was held in New York City.": False,
    "The goat is the national animal of Scotland.": False,
    "The Harry Potter film, Chamber of Secrets, is the longest film of the Harry Potter movies.": True,
    "The heart is the largest internal organ in the body.": False,
    "The human body has four lungs.": False,
    "The human body is about 60% water.": True,
    "The human eye can distinguish 10 million different colors.": True,
    "The hummingbird egg is the world's smallest bird egg.": True,
    "The largest living frog is the Goliath frog of West Africa.": True,
    "The letter \"J\" is the only letter in the alphabet not included in the periodic table.": True,
    "The letter \"T\" is the most common in the English Language.": False,
    "The maximum length for a video posted on TikTok is 45 seconds.": False,
    "The most common blood type is 0- negative.": True,
    "The name of Batman's butler is Albert.": False,
    "The names of the mascots for Rice Krispies are Snap, Crackle, & Pop.": True,
    "The New York Marathon is the largest in the world.": True,
    "The official color of the Golden Gate Bridge in California is \"Tennessee Orange.\"": False,
    "The song \"We Don't Talk About Bruno\" from Encanto is the first Disney song to hit #1 on the Billboard Hot 100 chart in 29 years.": True,
    "The total length of the Great Wall of China adds up to 13,171 miles.": True,
    "The Tour de France always finishes in Italy.": False,
    "The tradition of dyeing Easter eggs started in the United States.": False,
    "The two longest rivers in the world are the Mississippi and the Nile.": False,
    "The U.S. and Canada celebrate Thanksgiving on the same day.": False,
    "There are 30 NFL teams.": False,
    "There are more countries in South America than Africa.": False,
    "There are seven nights in Kwanzaa.": True,
    "Three strikes in a row in bowling is called a chicken.": False,
    "Toy Story was Pixar's first movie.": True,
    "Vanilla is the world's most expensive spice.": False,
    "Vatican City is the smallest country in the world.": True,
    "Venezuela is home to the world's highest waterfall.": True,
    "When exiting a cave, bats always go in the direction of the wind.": False,
    "World-renowned jeweler Tiffany & Co. is the maker of the Vince Lombardi trophy.": True,
    "You can find the 'Desert of Death' in California.": False
}
